application: gcdc2013-bangonph
version: master111620131740
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /favicon.ico
  static_files: frontend/img/favicon.ico
  upload: frontend/img/favicon.ico

- url: /(.*\.(ico))
  static_files: frontend/img/\1
  upload: frontend/img/(.*\.(ico))

- url: /robots.txt
  static_files: frontend/robots.txt
  upload: frontend/robots.txt

- url: /img
  static_dir: frontend/img
- url: /fonts
  static_dir: frontend/fonts
- url: /js
  static_dir: frontend/js
- url: /css
  static_dir: frontend/css
- url: /ico
  static_dir: frontend/ico

- url: /admin/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app

builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- warmup


error_handlers:
- file: frontend/500.html

- error_code: over_quota
  file: frontend/over_quota.html